<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<br /><font size = 2 color = #000000>Click on [settingsButton]</font>]]>
    </line>
    <line>
      <![CDATA[<br /><font size = 2 color = #000000>Click on [emailTemplatesButtton]</font>]]>
    </line>
    <line>
      <![CDATA[<br /><font size = 2 color = #000000>Click on [answerDuplicationTittle]</font>]]>
    </line>
    <line>
      <![CDATA[<br /><font size = 2 color = #000000>Click on [logginButton]</font>]]>
    </line>
    <line>
      <![CDATA[<br /><font size = 2 color = #000000>Click on [inputBoxRow]</font>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="25469" started-at="2015-01-19T10:23:03Z" finished-at="2015-01-19T10:23:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25469" started-at="2015-01-19T10:23:03Z" finished-at="2015-01-19T10:23:28Z">
      <class name="com.epam.testexternalpart.tests.AssigningToTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.epam.testexternalpart.tests.AssigningToTest@2c8d66b2]" name="init" is-config="true" duration-ms="6722" started-at="2015-01-19T12:23:03Z" finished-at="2015-01-19T12:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="startPage()[pri:0, instance:com.epam.testexternalpart.tests.AssigningToTest@2c8d66b2]" name="startPage" is-config="true" duration-ms="276" started-at="2015-01-19T12:23:10Z" finished-at="2015-01-19T12:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startPage -->
        <test-method status="FAIL" signature="checkDublicateAnswer()[pri:0, instance:com.epam.testexternalpart.tests.AssigningToTest@2c8d66b2]" name="checkDublicateAnswer" duration-ms="15580" started-at="2015-01-19T12:23:10Z" finished-at="2015-01-19T12:23:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.epam.testexternalpart.screen.stream.assigningTest.emails.AnswerFromIUa.checkDublicateAnswerMessage(AnswerFromIUa.java:120)
	at com.epam.testexternalpart.tests.AssigningToTest.checkDublicateAnswer(AssigningToTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br /><font size = 2 color = #000000>Click on [settingsButton]</font>]]>
            </line>
            <line>
              <![CDATA[<br /><font size = 2 color = #000000>Click on [emailTemplatesButtton]</font>]]>
            </line>
            <line>
              <![CDATA[<br /><font size = 2 color = #000000>Click on [answerDuplicationTittle]</font>]]>
            </line>
            <line>
              <![CDATA[<br /><font size = 2 color = #000000>Click on [logginButton]</font>]]>
            </line>
            <line>
              <![CDATA[<br /><font size = 2 color = #000000>Click on [inputBoxRow]</font>]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkDublicateAnswer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.epam.testexternalpart.tests.AssigningToTest@2c8d66b2]" name="tearDown" is-config="true" duration-ms="2873" started-at="2015-01-19T12:23:26Z" finished-at="2015-01-19T12:23:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.epam.testexternalpart.tests.AssigningToTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
