<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CandidateTest"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="158,986">
  <properties />
            <testcase name="deleteAllCandidates" time="7,719" classname="com.epam.testexternalpart.tests.AddCandidateTest">
                <failure type="java.lang.AssertionError"
                  message="expected [No matching records found] but found [1 Harry Potter James +380505465345 02-12-2013 sdhgjshg1j@mail.ru 09-01-2015]"
              >
<![CDATA[java.lang.AssertionError: expected [No matching records found] but found [1 Harry Potter James +380505465345 02-12-2013 sdhgjshg1j@mail.ru 09-01-2015]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.epam.testexternalpart.screen.Components.checkElementText(Components.java:107)
  com.epam.testexternalpart.screen.stream.StreamPage.deleteAllCand(StreamPage.java:650)
  com.epam.testexternalpart.tests.AddCandidateTest.deleteAllCandidates(AddCandidateTest.java:35)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:93)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
  com.sun.proxy.$Proxy0.invoke(Unknown Source)
  org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
  org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="changeStatus" time="122,150" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="addCandidateManually" time="7,402" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="bannWithButton" time="19,492" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="addCandidate" time="2,223" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
      
</testsuite>
