<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CandidateTest"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="42.977">
  <properties />
            <testcase name="changeStatus" time="17.352" classname="com.epam.testexternalpart.tests.AddCandidateTest">
                <failure type="java.lang.AssertionError"
                  message="Wrong data in new cand expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: Wrong data in new cand expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  com.epam.testexternalpart.screen.stream.StreamPage.checkCandExisting(StreamPage.java:487)
  com.epam.testexternalpart.tests.AddCandidateTest.changeStatus(AddCandidateTest.java:59)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
  org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
  org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="deleteAllCandidates" time="10.928" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="addCandidate" time="2.377" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="addCandidateManually" time="2.602" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
                <testcase name="bannWithButton" time="9.718" classname="com.epam.testexternalpart.tests.AddCandidateTest" />
      
</testsuite>
